Repository FinFellows/Server, pull requests merged in 2024-01, with the labels that each got.

#21 [FEAT] CI/CD 구성
  .github/workflows/deploy.yml
Labels: :sparkles: feature

#28 feat: Swagger 설정 추가 (#27)
  build.gradle
  src/main/java/com/finfellows/global/config/OpenApiConfig.java
Labels: :sparkles: feature

#18 Feat/#10 mypage view
  src/main/java/com/finfellows/domain/bookmark/application/BookmarkService.java
  src/main/java/com/finfellows/domain/bookmark/application/EduContentBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/FinancialProductBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/PolicyInfoBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/domain/EduContentBookmark.java
  src/main/java/com/finfellows/domain/bookmark/domain/FinancialProductBookmark.java
  src/main/java/com/finfellows/domain/bookmark/domain/PolicyInfoBookmark.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/EduContentBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/FinancialProductBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/PolicyInfoBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/dto/EduContentBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/FinancialProductBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/PolicyInfoBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/presentation/BookmarkController.java
  src/main/java/com/finfellows/domain/user/application/UserService.java
  src/main/java/com/finfellows/domain/user/presentation/UserController.java
Labels: :sparkles: feature

#17 [FEAT]#9 즐겨찾기 API 구현
  src/main/java/com/finfellows/domain/bookmark/application/EduContentBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/FinancialProductBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/PolicyInfoBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/EduContentBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/FinancialProductBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/PolicyInfoBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/dto/BookmarkRes.java
Labels: :sparkles: feature

#33 [FEAT]: User, Bookmark 기능 API 배포
  src/main/java/com/finfellows/domain/bookmark/application/BookmarkService.java
  src/main/java/com/finfellows/domain/bookmark/application/EduContentBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/FinancialProductBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/PolicyInfoBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/domain/EduContentBookmark.java
  src/main/java/com/finfellows/domain/bookmark/domain/FinancialProductBookmark.java
  src/main/java/com/finfellows/domain/bookmark/domain/PolicyInfoBookmark.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/EduContentBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/FinancialProductBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/PolicyInfoBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/dto/BookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/EduContentBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/FinancialProductBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/PolicyInfoBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/presentation/BookmarkController.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductRepository.java
  src/main/java/com/finfellows/domain/user/application/UserService.java
  src/main/java/com/finfellows/domain/user/presentation/UserController.java
Labels: :sparkles: feature

#36 [FEAT]: 예금 조회 API (조건 별 조회 가능) 구현
  build.gradle
  src/main/java/com/finfellows/domain/product/application/FinancialProductService.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/domain/FinancialProduct.java
  src/main/java/com/finfellows/domain/product/domain/FinancialProductOption.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepository.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductRepository.java
  src/main/java/com/finfellows/domain/product/dto/condition/DepositSearchCondition.java
  src/main/java/com/finfellows/domain/product/dto/response/SearchDepositPagingRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SearchDepositRes.java
  src/main/java/com/finfellows/domain/product/presentation/FinancialProductController.java
  src/main/java/com/finfellows/global/config/QueryDslConfig.java
  src/main/java/com/finfellows/global/config/security/SecurityConfig.java
  src/main/java/com/finfellows/global/payload/PagedResponse.java
Labels: :sparkles: feature

#37 [FEAT]: 예금 조회 API (조건 별 조회 가능) 구현
  build.gradle
  src/main/java/com/finfellows/domain/product/application/FinancialProductService.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/domain/FinancialProduct.java
  src/main/java/com/finfellows/domain/product/domain/FinancialProductOption.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepository.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductRepository.java
  src/main/java/com/finfellows/domain/product/dto/condition/DepositSearchCondition.java
  src/main/java/com/finfellows/domain/product/dto/response/SearchDepositPagingRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SearchDepositRes.java
  src/main/java/com/finfellows/domain/product/presentation/FinancialProductController.java
  src/main/java/com/finfellows/global/config/QueryDslConfig.java
  src/main/java/com/finfellows/global/config/security/SecurityConfig.java
  src/main/java/com/finfellows/global/payload/PagedResponse.java
Labels: :sparkles: feature

#41 [FEAT]: 예금/적금 관련 API 구현
  src/main/java/com/finfellows/domain/product/application/FinancialProductService.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductOptionRepository.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepository.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductRepository.java
  src/main/java/com/finfellows/domain/product/dto/condition/FinancialProductSearchCondition.java
  src/main/java/com/finfellows/domain/product/dto/response/DepositDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SavingDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SearchFinancialProductRes.java
  src/main/java/com/finfellows/domain/product/exception/InvalidFinancialProductException.java
  src/main/java/com/finfellows/domain/product/exception/ProductTypeMismatchException.java
  src/main/java/com/finfellows/domain/product/presentation/FinancialProductController.java
  src/main/java/com/finfellows/global/payload/PagedResponse.java
Labels: :sparkles: feature

#43 Feat/#10 mypage view
  src/main/java/com/finfellows/domain/bookmark/application/FinancialProductBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/PolicyInfoBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/FinancialProductBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/dto/EduContentBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/FinancialProductBookmarkRes.java
  src/main/java/com/finfellows/domain/user/presentation/UserController.java
Labels: documentation, :sparkles: feature

#46 [CHORE]: Swagger 관련 오류 수정
  src/main/java/com/finfellows/domain/bookmark/application/FinancialProductBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/PolicyInfoBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/FinancialProductBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/dto/EduContentBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/FinancialProductBookmarkRes.java
  src/main/java/com/finfellows/domain/product/presentation/FinancialProductController.java
  src/main/java/com/finfellows/domain/user/presentation/UserController.java
Labels: :bug: bug

#47 [FIX]: 예/적금 상품 조회 Bookmark 여부 Response 추가
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/domain/CMA.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepository.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/dto/response/SearchFinancialProductRes.java
Labels: :sparkles: feature

#51 [FEAT]: chatbot reaponse
  src/main/java/com/finfellows/domain/chatgpt/application/ChatGptService.java
  src/main/java/com/finfellows/domain/chatgpt/presentation/ChatGptController.java
  src/main/java/com/finfellows/domain/comment/application/CommentService.java
  src/main/java/com/finfellows/domain/comment/domain/Comment.java
  src/main/java/com/finfellows/domain/comment/domain/repository/CommentRepository.java
  src/main/java/com/finfellows/domain/comment/dto/request/CommentRequest.java
  src/main/java/com/finfellows/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/finfellows/domain/comment/presentation/CommentController.java
  src/main/java/com/finfellows/domain/educontent/dto/request/EduContentRequest.java
  src/main/java/com/finfellows/domain/educontent/dto/response/EduContentResponse.java
  src/main/java/com/finfellows/global/config/security/SecurityConfig.java
Labels: :sparkles: feature

#53 [FIX]: edu/news/content to enum
  src/main/java/com/finfellows/domain/chatgpt/application/ChatGptService.java
  src/main/java/com/finfellows/domain/comment/application/CommentService.java
  src/main/java/com/finfellows/domain/educontent/domain/EduContent.java
  src/main/java/com/finfellows/domain/educontent/dto/request/EduContentRequest.java
  src/main/java/com/finfellows/domain/educontent/dto/response/EduContentResponse.java
  src/main/java/com/finfellows/domain/newscontent/domain/NewsContent.java
  src/main/java/com/finfellows/domain/post/domain/Content.java
  src/main/java/com/finfellows/domain/post/domain/ContentType.java
  src/main/java/com/finfellows/domain/post/domain/Post.java
Labels: :sparkles: feature

#60 [FEAT]: 정책 상세 정보 API 구현
  src/main/java/com/finfellows/domain/policyinfo/application/PolicyInfoService.java
  src/main/java/com/finfellows/domain/policyinfo/application/PolicyInfoServiceImpl.java
  src/main/java/com/finfellows/domain/policyinfo/domain/repository/PolicyInfoQueryDslRepository.java
  src/main/java/com/finfellows/domain/policyinfo/domain/repository/PolicyInfoQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/policyinfo/dto/PolicyInfoDetailRes.java
  src/main/java/com/finfellows/domain/policyinfo/presentation/PolicyInfoController.java
Labels: :sparkles: feature

#61 [FEAT]: 정책 상세 정보 API 구현 (#60)
  src/main/java/com/finfellows/domain/policyinfo/application/PolicyInfoService.java
  src/main/java/com/finfellows/domain/policyinfo/application/PolicyInfoServiceImpl.java
  src/main/java/com/finfellows/domain/policyinfo/domain/repository/PolicyInfoQueryDslRepository.java
  src/main/java/com/finfellows/domain/policyinfo/domain/repository/PolicyInfoQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/policyinfo/dto/PolicyInfoDetailRes.java
  src/main/java/com/finfellows/domain/policyinfo/presentation/PolicyInfoController.java
Labels: :sparkles: feature

#62 [FEAT]: 정책 삭제/수정 API 구현
  src/main/java/com/finfellows/domain/policyinfo/application/PolicyInfoService.java
  src/main/java/com/finfellows/domain/policyinfo/application/PolicyInfoServiceImpl.java
  src/main/java/com/finfellows/domain/policyinfo/domain/PolicyInfo.java
  src/main/java/com/finfellows/domain/policyinfo/dto/PolicyUpdateReq.java
  src/main/java/com/finfellows/domain/policyinfo/exception/InvalidPolicyInfoException.java
  src/main/java/com/finfellows/domain/policyinfo/presentation/PolicyInfoController.java
Labels: :sparkles: feature

#63 [FEAT]: 정책 삭제/수정 API 구현 (#62)
  src/main/java/com/finfellows/domain/policyinfo/application/PolicyInfoService.java
  src/main/java/com/finfellows/domain/policyinfo/application/PolicyInfoServiceImpl.java
  src/main/java/com/finfellows/domain/policyinfo/domain/PolicyInfo.java
  src/main/java/com/finfellows/domain/policyinfo/dto/PolicyUpdateReq.java
  src/main/java/com/finfellows/domain/policyinfo/exception/InvalidPolicyInfoException.java
  src/main/java/com/finfellows/domain/policyinfo/presentation/PolicyInfoController.java
Labels: :sparkles: feature

#64 [HOTFIX]: CORS 오류 수정
  src/main/java/com/finfellows/global/config/security/WebMvcConfig.java
Labels: :bug: bug

#68 [REFACTOR]: refresh 메소드매핑, eduContentBookmark 관련 deprecated 코드 삭제, 카카오 code 발급 주석처리
  src/main/java/com/finfellows/domain/auth/presentation/AuthController.java
  src/main/java/com/finfellows/domain/bookmark/application/EduContentBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/FinancialProductBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/EduContentBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/dto/BookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/EduContentBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/presentation/BookmarkController.java
  src/main/java/com/finfellows/domain/user/presentation/UserController.java
Labels: :recycle: refactoring

#69 [FIX]: NewContent, EduContnet reponse 수정
  src/main/java/com/finfellows/domain/bookmark/domain/repository/EduContentBookmarkRepository.java
  src/main/java/com/finfellows/domain/educontent/application/EduContentService.java
  src/main/java/com/finfellows/domain/educontent/dto/response/EduContentResponse.java
  src/main/java/com/finfellows/domain/educontent/presentation/EduContentController.java
  src/main/java/com/finfellows/domain/newscontent/application/NewsContentService.java
  src/main/java/com/finfellows/domain/newscontent/dto/response/NewsContentResponse.java
  src/main/java/com/finfellows/domain/newscontent/presentation/NewsContentController.java
Labels: :bug: bug

#70 [DEPLOY]: 중간 배포
  src/main/java/com/finfellows/domain/auth/presentation/AuthController.java
  src/main/java/com/finfellows/domain/bookmark/application/EduContentBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/FinancialProductBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/EduContentBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/dto/BookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/EduContentBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/presentation/BookmarkController.java
  src/main/java/com/finfellows/domain/educontent/application/EduContentService.java
  src/main/java/com/finfellows/domain/educontent/dto/response/EduContentResponse.java
  src/main/java/com/finfellows/domain/educontent/presentation/EduContentController.java
  src/main/java/com/finfellows/domain/newscontent/application/NewsContentService.java
  src/main/java/com/finfellows/domain/newscontent/dto/response/NewsContentResponse.java
  src/main/java/com/finfellows/domain/newscontent/presentation/NewsContentController.java
  src/main/java/com/finfellows/domain/user/presentation/UserController.java
Labels: :sparkles: feature

#71 [FEAT]: CMA API 구현
  src/main/java/com/finfellows/domain/bookmark/application/BookmarkService.java
  src/main/java/com/finfellows/domain/bookmark/application/FinancialProductBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/domain/CmaBookmark.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/CmaBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/presentation/BookmarkController.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductService.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/domain/CmaType.java
  src/main/java/com/finfellows/domain/product/domain/repository/CmaRepository.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepository.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/dto/condition/CmaSearchCondition.java
  src/main/java/com/finfellows/domain/product/dto/response/CmaDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SearchCmaRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SearchDepositPagingRes.java
  src/main/java/com/finfellows/domain/product/presentation/FinancialProductController.java
Labels: :sparkles: feature

#74 [FEAT] cma 북마크 삭제기능 추가 , FinancialProduct 조회 기능을 수정
  src/main/java/com/finfellows/domain/bookmark/application/EduContentBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/FinancialProductBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/PolicyInfoBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/domain/CmaBookmark.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/CmaBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/EduContentBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/FinancialProductBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/PolicyInfoBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/dto/CmaBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/CmaFinancialProductBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/FinancialProductBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/presentation/BookmarkController.java
Labels: :sparkles: feature

#75 [FEAT] cma 북마크 삭제기능 추가 , FinancialProduct 조회 기능을 수정 (#74)
  src/main/java/com/finfellows/domain/bookmark/application/EduContentBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/FinancialProductBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/PolicyInfoBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/domain/CmaBookmark.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/CmaBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/EduContentBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/FinancialProductBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/PolicyInfoBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/dto/CmaBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/CmaFinancialProductBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/FinancialProductBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/presentation/BookmarkController.java
Labels: :sparkles: feature

#77 [REFACTOR]: 로그인 시 SecurityContextHolder에 인증정보 등록
  src/main/java/com/finfellows/domain/auth/application/KakaoService.java
  src/main/java/com/finfellows/domain/user/presentation/UserController.java
Labels: :recycle: refactoring

#84 [FIX]: contents request 수정
  src/main/java/com/finfellows/domain/bookmark/domain/repository/EduContentBookmarkRepository.java
  src/main/java/com/finfellows/domain/educontent/application/EduContentService.java
  src/main/java/com/finfellows/domain/educontent/dto/request/EduContentRequest.java
  src/main/java/com/finfellows/domain/educontent/presentation/EduContentController.java
  src/main/java/com/finfellows/domain/newscontent/application/NewsContentService.java
  src/main/java/com/finfellows/domain/newscontent/dto/request/NewsContentRequest.java
  src/main/java/com/finfellows/domain/newscontent/presentation/NewsContentController.java
  src/main/java/com/finfellows/domain/post/application/ContentService.java
  src/main/java/com/finfellows/domain/post/dto/request/ContentRequest.java
  src/main/java/com/finfellows/domain/post/presentation/ContentController.java
Labels: :bug: bug

#85 [FIX]: contents request 수정
  src/main/java/com/finfellows/domain/bookmark/domain/repository/EduContentBookmarkRepository.java
  src/main/java/com/finfellows/domain/educontent/application/EduContentService.java
  src/main/java/com/finfellows/domain/educontent/dto/request/EduContentRequest.java
  src/main/java/com/finfellows/domain/educontent/presentation/EduContentController.java
  src/main/java/com/finfellows/domain/newscontent/application/NewsContentService.java
  src/main/java/com/finfellows/domain/newscontent/dto/request/NewsContentRequest.java
  src/main/java/com/finfellows/domain/newscontent/presentation/NewsContentController.java
  src/main/java/com/finfellows/domain/post/application/ContentService.java
  src/main/java/com/finfellows/domain/post/dto/request/ContentRequest.java
  src/main/java/com/finfellows/domain/post/presentation/ContentController.java
Labels: :bug: bug

#87 [FIX] Paging Response 형식 수정
  src/main/java/com/finfellows/domain/policyinfo/application/PolicyInfoService.java
  src/main/java/com/finfellows/domain/policyinfo/application/PolicyInfoServiceImpl.java
  src/main/java/com/finfellows/domain/policyinfo/presentation/PolicyInfoController.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductService.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/dto/response/DepositDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SavingDetailRes.java
  src/main/java/com/finfellows/domain/product/presentation/FinancialProductController.java
  src/main/java/com/finfellows/global/config/security/SecurityConfig.java
  src/main/java/com/finfellows/global/payload/PagedResponse.java
Labels: :sparkles: feature

#88 [FIX] Paging Response 형식 수정 (#87)
  src/main/java/com/finfellows/domain/policyinfo/application/PolicyInfoService.java
  src/main/java/com/finfellows/domain/policyinfo/application/PolicyInfoServiceImpl.java
  src/main/java/com/finfellows/domain/policyinfo/presentation/PolicyInfoController.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductService.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/dto/response/DepositDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SavingDetailRes.java
  src/main/java/com/finfellows/domain/product/presentation/FinancialProductController.java
  src/main/java/com/finfellows/global/config/security/SecurityConfig.java
  src/main/java/com/finfellows/global/payload/PagedResponse.java
Labels: :sparkles: feature

#89 [FEAT]: edu contents pagination
  Dockerfile
  src/main/java/com/finfellows/domain/educontent/application/EduContentService.java
  src/main/java/com/finfellows/domain/educontent/presentation/EduContentController.java
  src/main/java/com/finfellows/domain/newscontent/application/NewsContentService.java
  src/main/java/com/finfellows/domain/newscontent/presentation/NewsContentController.java
  src/main/java/com/finfellows/domain/post/application/ContentService.java
  src/main/java/com/finfellows/domain/post/presentation/ContentController.java
Labels: :sparkles: feature

#92 [FIX]: userPrincipal null인 경우 조회 가능 수정
  src/main/java/com/finfellows/domain/educontent/dto/response/EduContentResponse.java
  src/main/java/com/finfellows/domain/educontent/presentation/EduContentController.java
  src/main/java/com/finfellows/domain/newscontent/dto/response/NewsContentResponse.java
  src/main/java/com/finfellows/domain/newscontent/presentation/NewsContentController.java
Labels: enhancement

#93 [FIX]: userPrincipal null인 경우 조회 가능 수정
  src/main/java/com/finfellows/domain/educontent/dto/response/EduContentResponse.java
  src/main/java/com/finfellows/domain/educontent/presentation/EduContentController.java
  src/main/java/com/finfellows/domain/newscontent/dto/response/NewsContentResponse.java
  src/main/java/com/finfellows/domain/newscontent/presentation/NewsContentController.java
Labels: enhancement

#96 [FIX]: 요청 사항 적용
  src/main/java/com/finfellows/domain/policyinfo/application/PolicyInfoServiceImpl.java
  src/main/java/com/finfellows/domain/policyinfo/domain/repository/PolicyInfoQueryDslRepository.java
  src/main/java/com/finfellows/domain/policyinfo/domain/repository/PolicyInfoQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepository.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/dto/condition/FinancialProductSearchCondition.java
  src/main/java/com/finfellows/global/config/OpenApiConfig.java
Labels: fix

#97 [FIX]: 요청 사항 적용 (#96)
  src/main/java/com/finfellows/domain/policyinfo/application/PolicyInfoServiceImpl.java
  src/main/java/com/finfellows/domain/policyinfo/domain/repository/PolicyInfoQueryDslRepository.java
  src/main/java/com/finfellows/domain/policyinfo/domain/repository/PolicyInfoQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepository.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/dto/condition/FinancialProductSearchCondition.java
  src/main/java/com/finfellows/global/config/OpenApiConfig.java
Labels: fix

#98 [CHORE]: Swagger 수정
  src/main/java/com/finfellows/global/config/OpenApiConfig.java
Labels: fix

#99 [CHORE]: Swagger 수정 (#98)
  src/main/java/com/finfellows/global/config/OpenApiConfig.java
Labels: fix

#101 [FIX]: 적금 조건 수정 (#100)
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
Labels: fix

#102 [REFACTOR]: orElseThrow 방식으로 리팩토링
  src/main/java/com/finfellows/domain/bookmark/application/EduContentBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/FinancialProductBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/PolicyInfoBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/PostBookmarkServiceImpl.java
Labels: :recycle: refactoring

#105 [REFACTOR]: orElseThrow 방식으로 리팩토링 (#102)
  src/main/java/com/finfellows/domain/bookmark/application/EduContentBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/FinancialProductBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/PolicyInfoBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/PostBookmarkServiceImpl.java
Labels: :recycle: refactoring

#106 [FIX] #94 챗봇 질문 request 수정
  src/main/java/com/finfellows/domain/comment/dto/request/CommentRequest.java
  src/main/java/com/finfellows/domain/comment/presentation/CommentController.java
Labels: enhancement

#108 [FIX]: 금융 상품 API 전체적으로 토큰 필요 없게 수정
  src/main/java/com/finfellows/domain/bookmark/domain/repository/CmaBookmarkRepository.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepository.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/dto/response/CmaDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SavingDetailRes.java
Labels: fix

#109 [FIX]: 금융 상품 API 전체적으로 토큰 필요 없게 수정 (#108)
  src/main/java/com/finfellows/domain/bookmark/domain/repository/CmaBookmarkRepository.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepository.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/dto/response/CmaDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SavingDetailRes.java
Labels: fix

#111 [FIX]: 배열 쿼리로 수정
  src/main/java/com/finfellows/domain/product/application/FinancialProductService.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/domain/Bank.java
  src/main/java/com/finfellows/domain/product/domain/repository/BankRepository.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepository.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/dto/condition/CmaSearchCondition.java
  src/main/java/com/finfellows/domain/product/dto/condition/DepositSearchCondition.java
  src/main/java/com/finfellows/domain/product/dto/condition/FinancialProductSearchCondition.java
  src/main/java/com/finfellows/domain/product/dto/request/BankUploadReq.java
  src/main/java/com/finfellows/domain/product/dto/response/CmaDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/DepositDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SavingDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SearchBankRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SearchCmaRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SearchDepositRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SearchFinancialProductRes.java
  src/main/java/com/finfellows/domain/product/presentation/FinancialProductController.java
Labels: fix

#112 [FIX]: 배열 쿼리로 수정 (#111)
  src/main/java/com/finfellows/domain/product/application/FinancialProductService.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/domain/Bank.java
  src/main/java/com/finfellows/domain/product/domain/repository/BankRepository.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepository.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/dto/condition/CmaSearchCondition.java
  src/main/java/com/finfellows/domain/product/dto/condition/DepositSearchCondition.java
  src/main/java/com/finfellows/domain/product/dto/condition/FinancialProductSearchCondition.java
  src/main/java/com/finfellows/domain/product/dto/request/BankUploadReq.java
  src/main/java/com/finfellows/domain/product/dto/response/CmaDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/DepositDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SavingDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SearchBankRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SearchCmaRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SearchDepositRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SearchFinancialProductRes.java
  src/main/java/com/finfellows/domain/product/presentation/FinancialProductController.java
Labels: fix

#113 [FIX]: URL Response 안되는 현상 수정
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/domain/repository/BankRepository.java
  src/main/java/com/finfellows/domain/product/dto/response/CmaDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/DepositDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SavingDetailRes.java
  src/main/java/com/finfellows/domain/product/presentation/FinancialProductController.java
Labels: fix

#114 [FIX]: URL Response 안되는 현상 수정 (#113)
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/domain/repository/BankRepository.java
  src/main/java/com/finfellows/domain/product/dto/response/CmaDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/DepositDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SavingDetailRes.java
  src/main/java/com/finfellows/domain/product/presentation/FinancialProductController.java
Labels: fix

#115 [HOTFIX]: 메소드 중복 제거
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
Labels: fix

#116 모든 금융, 뭐하지 북마크 삭제 api 추가
  src/main/java/com/finfellows/domain/bookmark/application/BookmarkCleanupService.java
  src/main/java/com/finfellows/domain/bookmark/application/FinancialProductBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/PolicyInfoBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/application/PostBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/CmaBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/presentation/BookmarkController.java
Labels: :sparkles: feature

#120 CMA 엔티티 명에 따른 JPQL 작성
  src/main/java/com/finfellows/domain/bookmark/domain/repository/CmaBookmarkRepository.java
Labels: fix

#121 CMA 엔티티 명에 따른 JPQL 작성
  src/main/java/com/finfellows/domain/bookmark/domain/repository/CmaBookmarkRepository.java
  src/main/java/com/finfellows/domain/post/domain/Content.java
Labels: fix

#126 [FEAT] 마이페이지 조회 API에서 상품 ID를 함께 응답한다.
  src/main/java/com/finfellows/domain/bookmark/dto/CmaBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/FinancialProductBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/PolicyInfoBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/PostBookmarkRes.java
Labels: :sparkles: feature

#127 마이페이지 조회 API에서 상품 ID를 함께 응답한다.
  src/main/java/com/finfellows/domain/bookmark/dto/CmaBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/FinancialProductBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/PolicyInfoBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/PostBookmarkRes.java
Labels: :sparkles: feature

#131 [FIX] 금융상품 조회 시 중복 데이터 제거, 이율 타입 별 정렬 기준 기능 추가
  build.gradle
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductOptionOrderByDefault.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductOptionOrderByMax.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/dto/condition/FinancialProductSearchCondition.java
Labels: :sparkles: feature, fix

#132 [FIX] 금융상품 조회 시 중복 데이터 제거, 이율 타입 별 정렬 기준 기능 추가 (#131)
  build.gradle
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductOptionOrderByDefault.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductOptionOrderByMax.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/dto/condition/FinancialProductSearchCondition.java
Labels: :sparkles: feature, fix

#134 [FIX]:s3 image upload
  build.gradle
  src/main/java/com/finfellows/domain/image/application/ImageService.java
  src/main/java/com/finfellows/domain/image/dto/request/ImageRequest.java
  src/main/java/com/finfellows/domain/image/dto/response/ImageResponse.java
  src/main/java/com/finfellows/domain/image/presentation/ImageControlller.java
  src/main/java/com/finfellows/global/config/AmazonS3Config.java
Labels: :sparkles: feature

#135 S3 버킷 이미지 업로드 및 url 변환 api 구현
  build.gradle
  src/main/java/com/finfellows/domain/image/application/ImageService.java
  src/main/java/com/finfellows/domain/image/dto/request/ImageRequest.java
  src/main/java/com/finfellows/domain/image/dto/response/ImageResponse.java
  src/main/java/com/finfellows/domain/image/presentation/ImageControlller.java
  src/main/java/com/finfellows/global/config/AmazonS3Config.java
Labels: :sparkles: feature

#136 [FEAT] #133 swagger 코드 수정
  src/main/java/com/finfellows/domain/image/dto/request/ImageRequest.java
  src/main/java/com/finfellows/domain/image/presentation/ImageControlller.java
Labels: fix

#139 [FIX] swagger 코드 수정
  src/main/java/com/finfellows/domain/educontent/presentation/EduContentController.java
  src/main/java/com/finfellows/domain/image/presentation/ImageControlller.java
  src/main/java/com/finfellows/domain/newscontent/presentation/NewsContentController.java
Labels: enhancement

#140 Swagger 코드 수정
  src/main/java/com/finfellows/domain/educontent/presentation/EduContentController.java
  src/main/java/com/finfellows/domain/image/presentation/ImageControlller.java
  src/main/java/com/finfellows/domain/newscontent/presentation/NewsContentController.java
Labels: enhancement

#141 [FIX]: 은행 이름으로 조회 오류 수정
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
Labels: fix

#142 [FIX]: 은행 이름으로 조회 오류 수정 (#141)
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
Labels: fix

#144 [FEAT] refreshToken 쿠키 저장 구현
  src/main/java/com/finfellows/domain/auth/application/KakaoService.java
  src/main/java/com/finfellows/domain/auth/presentation/AuthController.java
Labels: :sparkles: feature

#146 [FEAT] 토큰 갱신 api 수정
  src/main/java/com/finfellows/domain/auth/application/KakaoService.java
  src/main/java/com/finfellows/domain/auth/presentation/AuthController.java
Labels: :sparkles: feature

#149 [FEAT] 북마크 조회 response에 isLiked==True 추가
  src/main/java/com/finfellows/domain/bookmark/dto/CmaBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/FinancialProductBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/PolicyInfoBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/PostBookmarkRes.java
Labels: :sparkles: feature

#150 isLiked 여부를 북마크 조회 response에 포함
  src/main/java/com/finfellows/domain/bookmark/dto/CmaBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/FinancialProductBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/PolicyInfoBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/PostBookmarkRes.java
Labels: :sparkles: feature

#152 [FIX]: 엔티티 스팩 변경 및 CMA API 구현 완료
  src/main/java/com/finfellows/domain/bookmark/dto/CmaBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/FinancialProductBookmarkRes.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/domain/Bank.java
  src/main/java/com/finfellows/domain/product/domain/CMA.java
  src/main/java/com/finfellows/domain/product/domain/FinancialProduct.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductOptionOrderByDefault.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductOptionOrderByMax.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/dto/response/CmaDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/DepositDetailRes.java
  src/main/java/com/finfellows/domain/product/dto/response/SavingDetailRes.java
  src/main/java/com/finfellows/domain/product/presentation/FinancialProductController.java
Labels: fix

#154 [FIX] 금융, 배우자 북마크 기능 및 엔티티 수정
  src/main/java/com/finfellows/domain/bookmark/application/PostBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/domain/NewsContentBookmark.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/NewsContentBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/dto/EduContentBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/EduContentNewsContentBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/NewsContentBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/presentation/BookmarkController.java
Labels: :sparkles: feature

#155 [FIX] 금융, 배우자 북마크 기능 및 엔티티 수정
  src/main/java/com/finfellows/domain/bookmark/application/PostBookmarkServiceImpl.java
  src/main/java/com/finfellows/domain/bookmark/domain/NewsContentBookmark.java
  src/main/java/com/finfellows/domain/bookmark/domain/repository/NewsContentBookmarkRepository.java
  src/main/java/com/finfellows/domain/bookmark/dto/EduContentBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/EduContentNewsContentBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/dto/NewsContentBookmarkRes.java
  src/main/java/com/finfellows/domain/bookmark/presentation/BookmarkController.java
Labels: fix

#156 [FIX] 유저 로그아웃 로직 변경
  src/main/java/com/finfellows/domain/auth/application/KakaoService.java
  src/main/java/com/finfellows/domain/auth/presentation/AuthController.java
Labels: fix

#157 [FIX] 유저 로그아웃 로직 변경
  src/main/java/com/finfellows/domain/auth/application/KakaoService.java
  src/main/java/com/finfellows/domain/auth/presentation/AuthController.java
Labels: fix

#158 [FIX]: Terms 조건 안되는 현상 수정
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
Labels: fix

#160 [FIX]: Tems 조건 조회 안되는 현상 수정
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
Labels: fix

#167 [FIX] exposedHeader 설정
  src/main/java/com/finfellows/domain/auth/application/KakaoService.java
  src/main/java/com/finfellows/global/config/security/WebMvcConfig.java
Labels: fix

#168 [FIX] exposedHeader 추가
  src/main/java/com/finfellows/domain/auth/application/KakaoService.java
  src/main/java/com/finfellows/global/config/security/WebMvcConfig.java
Labels: fix

#171 [FIX]: Term 정렬 조건 FIX + 최대 금액 조건 추가
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductOptionOrderByDefault.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductOptionOrderByMax.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/dto/condition/FinancialProductSearchCondition.java
  src/main/java/com/finfellows/domain/product/presentation/FinancialProductController.java
Labels: fix

#172 [FIX]: Term 정렬 조건 FIX + 최대 금액 조건 추가 (#171)
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductOptionOrderByDefault.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductOptionOrderByMax.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
  src/main/java/com/finfellows/domain/product/dto/condition/FinancialProductSearchCondition.java
  src/main/java/com/finfellows/domain/product/presentation/FinancialProductController.java
Labels: fix

#173 [FiX]: 최대 금액 조건 오류 수정
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
Labels: fix

#174 [FiX]: 최대 금액 조건 오류 수정 (#173)
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
Labels: fix

#175 [FEAT]: 예금 계산기 API 구현
  src/main/java/com/finfellows/domain/product/application/FinancialProductService.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/dto/response/DepositCalculateRes.java
  src/main/java/com/finfellows/domain/product/presentation/FinancialProductController.java
Labels: :sparkles: feature

#176 [FEAT]: 예금 계산기 API 구현 (#175)
  src/main/java/com/finfellows/domain/product/application/FinancialProductService.java
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/dto/response/DepositCalculateRes.java
  src/main/java/com/finfellows/domain/product/presentation/FinancialProductController.java
Labels: :sparkles: feature

#196 [FIX]: 예금 계산기 계산 방식 변경 + maxLimit 정렬 조건 수정
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
Labels: fix

#197 [FIX]: 예금 계산기 계산 방식 변경 + maxLimit 정렬 조건 수정 (#196)
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/domain/repository/FinancialProductQueryDslRepositoryImpl.java
Labels: fix

#200 [FIX]: policy detail 토큰 없이도 조회 가능하게 변경 (#199)
  src/main/java/com/finfellows/domain/policyinfo/application/PolicyInfoServiceImpl.java
  src/main/java/com/finfellows/domain/policyinfo/domain/repository/PolicyInfoQueryDslRepository.java
  src/main/java/com/finfellows/domain/policyinfo/domain/repository/PolicyInfoQueryDslRepositoryImpl.java
Labels: fix

#203 [FIX]: 예금 계산기 12개월 옵션으로 고정
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/dto/response/DepositCalculateRes.java
Labels: fix

#204 [FIX]: 예금 계산기 12개월 옵션으로 고정 (#203)
  src/main/java/com/finfellows/domain/product/application/FinancialProductServiceImpl.java
  src/main/java/com/finfellows/domain/product/dto/response/DepositCalculateRes.java
Labels: fix
